name: Multiline commad execution

on: push

jobs:
    first-job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v6  

            - name: Multiline commad execution
              run:  |
                echo "Multiline commad execution job"
                ls -ltra
                cat README.md